//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Changes to this file will be lost if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using EnchantedCoder.Data.EntityFrameworkCore.Patterns.DataSources.Fakes;
using EnchantedCoder.Data.EntityFrameworkCore.Patterns.SoftDeletes;
using EnchantedCoder.Data.Patterns.Attributes;

namespace EnchantedCoder.EFCoreTests.DataLayer.DataSources.Fakes;

[Fake]
[System.CodeDom.Compiler.GeneratedCode("EnchantedCoder.Data.EntityFrameworkCore.CodeGenerator", "1.0")]
public class FakeModelationDataSource : FakeDataSource<EnchantedCoder.EFCoreTests.Model.Modelation>, EnchantedCoder.EFCoreTests.DataLayer.DataSources.IModelationDataSource
{
	public FakeModelationDataSource(params EnchantedCoder.EFCoreTests.Model.Modelation[] data)
		: this((IEnumerable<EnchantedCoder.EFCoreTests.Model.Modelation>)data)
	{
	}

	public FakeModelationDataSource(IEnumerable<EnchantedCoder.EFCoreTests.Model.Modelation> data, ISoftDeleteManager softDeleteManager = null)
		: base(data, softDeleteManager)
	{
	}
}
