//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Changes to this file will be lost if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using EnchantedCoder.Data.EntityFrameworkCore.Patterns.DataSources.Fakes;
using EnchantedCoder.Data.EntityFrameworkCore.Patterns.SoftDeletes;
using EnchantedCoder.Data.Patterns.Attributes;

namespace EnchantedCoder.EFCoreTests.DataLayer.DataSources.Fakes;

[Fake]
[System.CodeDom.Compiler.GeneratedCode("EnchantedCoder.Data.EntityFrameworkCore.CodeGenerator", "1.0")]
public class FakeUserDataSource : FakeDataSource<EnchantedCoder.EFCoreTests.Model.User>, EnchantedCoder.EFCoreTests.DataLayer.DataSources.IUserDataSource
{
	public FakeUserDataSource(params EnchantedCoder.EFCoreTests.Model.User[] data)
		: this((IEnumerable<EnchantedCoder.EFCoreTests.Model.User>)data)
	{
	}

	public FakeUserDataSource(IEnumerable<EnchantedCoder.EFCoreTests.Model.User> data, ISoftDeleteManager softDeleteManager = null)
		: base(data, softDeleteManager)
	{
	}
}
