//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Changes to this file will be lost if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using EnchantedCoder.Data.EntityFrameworkCore.Patterns.DataSources.Fakes;
using EnchantedCoder.Data.EntityFrameworkCore.Patterns.SoftDeletes;
using EnchantedCoder.Data.Patterns.Attributes;

namespace EnchantedCoder.EFCoreTests.DataLayer.DataSources.Fakes;

[Fake]
[System.CodeDom.Compiler.GeneratedCode("EnchantedCoder.Data.EntityFrameworkCore.CodeGenerator", "1.0")]
public class FakePersonDataSource : FakeDataSource<EnchantedCoder.EFCoreTests.Model.Person>, EnchantedCoder.EFCoreTests.DataLayer.DataSources.IPersonDataSource
{
	public FakePersonDataSource(params EnchantedCoder.EFCoreTests.Model.Person[] data)
		: this((IEnumerable<EnchantedCoder.EFCoreTests.Model.Person>)data)
	{
	}

	public FakePersonDataSource(IEnumerable<EnchantedCoder.EFCoreTests.Model.Person> data, ISoftDeleteManager softDeleteManager = null)
		: base(data, softDeleteManager)
	{
	}
}
