//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Changes to this file will be lost if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using EnchantedCoder.Data.EntityFrameworkCore.Patterns.DataSources.Fakes;
using EnchantedCoder.Data.EntityFrameworkCore.Patterns.SoftDeletes;
using EnchantedCoder.Data.Patterns.Attributes;

namespace EnchantedCoder.EFCoreTests.DataLayer.DataSources.Fakes;

[Fake]
[System.CodeDom.Compiler.GeneratedCode("EnchantedCoder.Data.EntityFrameworkCore.CodeGenerator", "1.0")]
public class FakeAddressDataSource : FakeDataSource<EnchantedCoder.EFCoreTests.Model.Address>, EnchantedCoder.EFCoreTests.DataLayer.DataSources.IAddressDataSource
{
	public FakeAddressDataSource(params EnchantedCoder.EFCoreTests.Model.Address[] data)
		: this((IEnumerable<EnchantedCoder.EFCoreTests.Model.Address>)data)
	{
	}

	public FakeAddressDataSource(IEnumerable<EnchantedCoder.EFCoreTests.Model.Address> data, ISoftDeleteManager softDeleteManager = null)
		: base(data, softDeleteManager)
	{
	}
}
