//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Changes to this file will be lost if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using EnchantedCoder.Data.EntityFrameworkCore.Patterns.DataSources.Fakes;
using EnchantedCoder.Data.EntityFrameworkCore.Patterns.SoftDeletes;
using EnchantedCoder.Data.Patterns.Attributes;

namespace EnchantedCoder.EFCoreTests.DataLayer.DataSources.Fakes;

[Fake]
[System.CodeDom.Compiler.GeneratedCode("EnchantedCoder.Data.EntityFrameworkCore.CodeGenerator", "1.0")]
public class FakeBusinessCaseDataSource : FakeDataSource<EnchantedCoder.EFCoreTests.Model.BusinessCase>, EnchantedCoder.EFCoreTests.DataLayer.DataSources.IBusinessCaseDataSource
{
	public FakeBusinessCaseDataSource(params EnchantedCoder.EFCoreTests.Model.BusinessCase[] data)
		: this((IEnumerable<EnchantedCoder.EFCoreTests.Model.BusinessCase>)data)
	{
	}

	public FakeBusinessCaseDataSource(IEnumerable<EnchantedCoder.EFCoreTests.Model.BusinessCase> data, ISoftDeleteManager softDeleteManager = null)
		: base(data, softDeleteManager)
	{
	}
}
