//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Changes to this file will be lost if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using EnchantedCoder.Data.EntityFrameworkCore.Patterns.DataSources.Fakes;
using EnchantedCoder.Data.EntityFrameworkCore.Patterns.SoftDeletes;
using EnchantedCoder.Data.Patterns.Attributes;

namespace EnchantedCoder.EFCoreTests.DataLayer.DataSources.Fakes;

[Fake]
[System.CodeDom.Compiler.GeneratedCode("EnchantedCoder.Data.EntityFrameworkCore.CodeGenerator", "1.0")]
public class FakePropertyWithProtectedMembersDataSource : FakeDataSource<EnchantedCoder.EFCoreTests.Model.PropertyWithProtectedMembers>, EnchantedCoder.EFCoreTests.DataLayer.DataSources.IPropertyWithProtectedMembersDataSource
{
	public FakePropertyWithProtectedMembersDataSource(params EnchantedCoder.EFCoreTests.Model.PropertyWithProtectedMembers[] data)
		: this((IEnumerable<EnchantedCoder.EFCoreTests.Model.PropertyWithProtectedMembers>)data)
	{
	}

	public FakePropertyWithProtectedMembersDataSource(IEnumerable<EnchantedCoder.EFCoreTests.Model.PropertyWithProtectedMembers> data, ISoftDeleteManager softDeleteManager = null)
		: base(data, softDeleteManager)
	{
	}
}
