//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Changes to this file will be lost if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using EnchantedCoder.Data.EntityFrameworkCore.Patterns.DataSources.Fakes;
using EnchantedCoder.Data.EntityFrameworkCore.Patterns.SoftDeletes;
using EnchantedCoder.Data.Patterns.Attributes;

namespace EnchantedCoder.EFCoreTests.DataLayer.DataSources.Fakes;

[Fake]
[System.CodeDom.Compiler.GeneratedCode("EnchantedCoder.Data.EntityFrameworkCore.CodeGenerator", "1.0")]
public class FakeCheckedEntityDataSource : FakeDataSource<EnchantedCoder.EFCoreTests.Model.CheckedEntity>, EnchantedCoder.EFCoreTests.DataLayer.DataSources.ICheckedEntityDataSource
{
	public FakeCheckedEntityDataSource(params EnchantedCoder.EFCoreTests.Model.CheckedEntity[] data)
		: this((IEnumerable<EnchantedCoder.EFCoreTests.Model.CheckedEntity>)data)
	{
	}

	public FakeCheckedEntityDataSource(IEnumerable<EnchantedCoder.EFCoreTests.Model.CheckedEntity> data, ISoftDeleteManager softDeleteManager = null)
		: base(data, softDeleteManager)
	{
	}
}
