//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Changes to this file will be lost if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using EnchantedCoder.Data.Patterns.DataSources;

namespace EnchantedCoder.EFCoreTests.DataLayer.DataSources;

[System.CodeDom.Compiler.GeneratedCode("EnchantedCoder.Data.EntityFrameworkCore.CodeGenerator", "1.0")]
public interface ICheckedEntityDataSource : IDataSource<EnchantedCoder.EFCoreTests.Model.CheckedEntity>
{
}
