//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Changes to this file will be lost if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using EnchantedCoder.Data.Patterns.Repositories;

namespace EnchantedCoder.EFCoreTests.DataLayer.Repositories;

[System.CodeDom.Compiler.GeneratedCode("EnchantedCoder.Data.EntityFrameworkCore.CodeGenerator", "1.0")]
public partial interface IBusinessCaseRepository : IRepository<EnchantedCoder.EFCoreTests.Model.BusinessCase>
{
}
